### ISSUE TITLE
Link to travis build on readme is broken

### ISSUE THREAD

**Issue by cyberhck** [crazyfactory/ts-module-boilerplate#2]
Currently it's pointing to `travis-ci.com/crazyfactory/ts-module-boilerplate` but it should point to `travis-ci.org/crazyfactory/ts-module-boilerplate`

**Comment by wmathes** [comment]
Whoops, yes. that's correct

**Comment by wmathes** [comment]
ALso while at it:
the issues badge should link to https://github.com/crazyfactory/ts-module-boilerplate/issues

**Comment by cyberhck** [comment]
closed by #3
