### ISSUE TITLE
Is "karma-es6-shim" more elegant?

### ISSUE THREAD

**Issue by wmathes** [crazyfactory/ts-module-boilerplate#4]
There's a package called `karma-es6-shim`. It installed simply by registering it as a framework in the karma.conf.js. 

Using this could possibly spare us of the extra configurations done in `.travis.yml` (sudo: true, trust dis, addon firefox...) to get old versions of phantomJS/firefox/chromium to work. 

Someone can try it out and report back with results :)

Also: Don't break wallaby please :p

**Comment by cyberhck** [comment]
Since I've already got wallaby working, I'll give this a try

**Comment by wmathes** [comment]
Status?
